import SwiftUI

struct DailySummaryView: View {
    let db: DatabaseManager
    let date: String
    @State private var summary: DailySummaryRecord?
    @State private var isGenerating = false
    @State private var errorMessage: String?

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                HStack {
                    Text("Daily Summary — \(date)")
                        .font(.title2).fontWeight(.semibold)
                    Spacer()
                    Button(isGenerating ? "Generating..." : "Regenerate") {
                        Task { await regenerateSummary() }
                    }
                    .disabled(isGenerating)
                }

                if let errorMessage {
                    Text(errorMessage).foregroundStyle(.red).font(.caption)
                }

                if let summary {
                    if let text = summary.summaryText {
                        Text("Summary").font(.headline)
                        Text(text)
                    }

                    if let model = summary.modelName {
                        Text("Generated by \(model)")
                            .font(.caption2).foregroundStyle(.tertiary)
                    }
                } else {
                    Text("No summary generated yet.")
                        .foregroundStyle(.secondary)
                }
            }
            .padding()
        }
        .frame(minWidth: 400, minHeight: 300)
        .onAppear { loadSummary() }
    }

    private func loadSummary() {
        let provider = TimelineDataProvider(db: db)
        summary = try? provider.dailySummary(for: date)
    }

    @MainActor
    private func regenerateSummary() async {
        let settings = AppSettings()
        guard let client = LLMClient.client(for: settings) else {
            errorMessage = "Summary provider is disabled or incomplete in Settings."
            return
        }
        isGenerating = true
        errorMessage = nil
        let capturedDB = db
        let targetDate = date
        do {
            let summarizer = DailySummarizer(db: capturedDB)
            summary = try await summarizer.summarize(for: targetDate, using: client)
        } catch {
            errorMessage = error.localizedDescription
        }
        isGenerating = false
    }
}
